---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        auth_pass: "{{ auth_pass }}"
        authorize: "{{ authorize }}"
        backup: "{{ backup }}"

  - name: suppress confirmations
    ios_config:
      provider: "{{ provider }}"
      lines:
        - file prompt quiet

  - name: take backup config
    ios_command:
      provider: "{{ provider }}"
      commands:
        - copy running-config flash://startup-config.original

  - name: re-enable confirmations
    ios_config:
      provider: "{{ provider }}"
      lines:
        - file prompt alert
